// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/checkin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================
// 📋 签到请求消息
// ==========================
type UserCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 签到时间戳
	CheckinType string `protobuf:"bytes,3,opt,name=checkin_type,json=checkinType,proto3" json:"checkin_type,omitempty"` // 签到类型：normal/补签/活动签到
}

func (x *UserCheckinRequest) Reset() {
	*x = UserCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_checkin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckinRequest) ProtoMessage() {}

func (x *UserCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckinRequest.ProtoReflect.Descriptor instead.
func (*UserCheckinRequest) Descriptor() ([]byte, []int) {
	return file_pb_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *UserCheckinRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCheckinRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserCheckinRequest) GetCheckinType() string {
	if x != nil {
		return x.CheckinType
	}
	return ""
}

// ==========================
// 📊 签到响应消息
// ==========================
type UserCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success          bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // 是否成功
	Message          string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                      // 提示信息
	ContinuousDays   int32  `protobuf:"varint,3,opt,name=continuous_days,json=continuousDays,proto3" json:"continuous_days,omitempty"` // 连续签到天数
	TotalDays        int32  `protobuf:"varint,4,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`                // 总签到天数
	RemainRetroTimes int32  `protobuf:"varint,5,opt,name=remain_retro_times,json=remainRetroTimes,proto3" json:"remain_retro_times,omitempty"`
}

func (x *UserCheckinResponse) Reset() {
	*x = UserCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_checkin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckinResponse) ProtoMessage() {}

func (x *UserCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckinResponse.ProtoReflect.Descriptor instead.
func (*UserCheckinResponse) Descriptor() ([]byte, []int) {
	return file_pb_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *UserCheckinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserCheckinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserCheckinResponse) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *UserCheckinResponse) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *UserCheckinResponse) GetRemainRetroTimes() int32 {
	if x != nil {
		return x.RemainRetroTimes
	}
	return 0
}

// ==========================
// 🔍 签到状态查询请求
// ==========================
type CheckinStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *CheckinStatusRequest) Reset() {
	*x = CheckinStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_checkin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinStatusRequest) ProtoMessage() {}

func (x *CheckinStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckinStatusRequest) Descriptor() ([]byte, []int) {
	return file_pb_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *CheckinStatusRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckinStatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==========================
// 📈 签到状态查询响应
// ==========================
type CheckinStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckedInDays      []int32 `protobuf:"varint,1,rep,packed,name=checked_in_days,json=checkedInDays,proto3" json:"checked_in_days,omitempty"`                  // 当月签到日期序号，使用repeated表示数组
	RetroCheckedInDays []int32 `protobuf:"varint,2,rep,packed,name=retro_checked_in_days,json=retroCheckedInDays,proto3" json:"retro_checked_in_days,omitempty"` // 当月补签日期序号，使用repeated表示数组
}

func (x *CheckinStatusResponse) Reset() {
	*x = CheckinStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_checkin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinStatusResponse) ProtoMessage() {}

func (x *CheckinStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_checkin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckinStatusResponse) Descriptor() ([]byte, []int) {
	return file_pb_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *CheckinStatusResponse) GetCheckedInDays() []int32 {
	if x != nil {
		return x.CheckedInDays
	}
	return nil
}

func (x *CheckinStatusResponse) GetRetroCheckedInDays() []int32 {
	if x != nil {
		return x.RetroCheckedInDays
	}
	return nil
}

var File_pb_checkin_proto protoreflect.FileDescriptor

var file_pb_checkin_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6e, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73,
	0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x79, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x74, 0x72, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x72, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x64,
	0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x64, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x72, 0x65, 0x74, 0x72,
	0x6f, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x12, 0x72, 0x65, 0x74, 0x72, 0x6f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x64, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x32, 0x99, 0x01, 0x0a, 0x0e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x12, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x62, 0x6c, 0x75, 0x65, 0x62,
	0x65, 0x6c, 0x6c, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_checkin_proto_rawDescOnce sync.Once
	file_pb_checkin_proto_rawDescData = file_pb_checkin_proto_rawDesc
)

func file_pb_checkin_proto_rawDescGZIP() []byte {
	file_pb_checkin_proto_rawDescOnce.Do(func() {
		file_pb_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_checkin_proto_rawDescData)
	})
	return file_pb_checkin_proto_rawDescData
}

var file_pb_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_checkin_proto_goTypes = []interface{}{
	(*UserCheckinRequest)(nil),    // 0: pb.UserCheckinRequest
	(*UserCheckinResponse)(nil),   // 1: pb.UserCheckinResponse
	(*CheckinStatusRequest)(nil),  // 2: pb.CheckinStatusRequest
	(*CheckinStatusResponse)(nil), // 3: pb.CheckinStatusResponse
}
var file_pb_checkin_proto_depIdxs = []int32{
	0, // 0: pb.CheckinService.UserCheckin:input_type -> pb.UserCheckinRequest
	2, // 1: pb.CheckinService.GetCheckinStatus:input_type -> pb.CheckinStatusRequest
	1, // 2: pb.CheckinService.UserCheckin:output_type -> pb.UserCheckinResponse
	3, // 3: pb.CheckinService.GetCheckinStatus:output_type -> pb.CheckinStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_checkin_proto_init() }
func file_pb_checkin_proto_init() {
	if File_pb_checkin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_checkin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_checkin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_checkin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_checkin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_checkin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_checkin_proto_goTypes,
		DependencyIndexes: file_pb_checkin_proto_depIdxs,
		MessageInfos:      file_pb_checkin_proto_msgTypes,
	}.Build()
	File_pb_checkin_proto = out.File
	file_pb_checkin_proto_rawDesc = nil
	file_pb_checkin_proto_goTypes = nil
	file_pb_checkin_proto_depIdxs = nil
}
